<template>
  <div class="report-detail">
    <div v-if="report" class="detail-container" ref="pdfTarget">
      <div class="header-row no-print">
        <button class="back" @click="goBack">← Back</button>
        <button class="download" @click="downloadPdf" :disabled="downloading">
          {{ downloading ? 'Preparing…' : 'Download' }}
        </button>
      </div>
      <div class="meta-line">
        <span>{{ formatDateTime(report.generated_at) }}</span>
      </div>
      <h1 class="title">Weekly Activity Report</h1>
      <p class="subtitle">
        Cantilan National High School – Library Inventory System<br />Report Period:
        {{ rangeLabel }}
      </p>
      <p class="generated-by">Generated By: Librarian Name</p>
      <hr />
      <section class="summary-section">
        <h2 class="section-heading">Summary</h2>
        <ul class="summary-list">
          <li>Books Borrowed: {{ report.summary.borrowed }}</li>
          <li>Books Returned: {{ report.summary.returned }}</li>
          <li>Overdue Books: {{ report.summary.overdue }}</li>
          <li>New Members: {{ report.summary.new_members }}</li>
        </ul>
      </section>
      <hr />
      <section class="daily-section">
        <h2 class="section-heading">Daily Activity Table</h2>
        <table class="daily-table">
          <thead>
            <tr>
              <th>Date</th>
              <th>Borrowed</th>
              <th>Returned</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="row in report.daily" :key="row.label">
              <td>{{ row.label }}</td>
              <td>{{ row.borrowed }}</td>
              <td>{{ row.returned }}</td>
            </tr>
          </tbody>
        </table>
      </section>
      <section class="recommend-section">
        <h2 class="section-heading">Recommendations</h2>
        <ul class="rec-list">
          <li v-for="(r, i) in report.recommendations" :key="i">{{ r }}</li>
        </ul>
      </section>
    </div>
    <p v-else class="not-found">
      Report not found. <button class="back" @click="goBack">Return</button>
    </p>
  </div>
</template>
<script setup>
import { ref, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useReportsStore } from '@/stores/reports'
import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

const route = useRoute()
const router = useRouter()
const reports = useReportsStore()
const pdfTarget = ref(null)
const downloading = ref(false)

reports.setCurrent(route.params.id)
const report = computed(() => reports.current)

function formatDateTime(iso) {
  const d = new Date(iso)
  return `${d.getMonth() + 1}-${d.getDate()}-${d.getFullYear()}  ${d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`
}
const rangeLabel = computed(() => {
  if (!report.value) return ''
  const s = new Date(report.value.start)
  const e = new Date(report.value.end)
  const opt = { month: 'long', day: 'numeric' }
  return `${s.toLocaleDateString(undefined, opt)} – ${e.toLocaleDateString(undefined, opt)}, ${e.getFullYear()}`
})

async function downloadPdf() {
  if (!pdfTarget.value || !report.value) return
  downloading.value = true
  try {
    const canvas = await html2canvas(pdfTarget.value, {
      scale: 2,
      ignoreElements: (el) => el.classList && el.classList.contains('no-print'),
    })
    const imgData = canvas.toDataURL('image/png')
    const pdf = new jsPDF('p', 'pt', 'a4')
    const pageWidth = pdf.internal.pageSize.getWidth()
    const imgWidth = pageWidth - 40
    const imgHeight = canvas.height * (imgWidth / canvas.width)
    let y = 20
    pdf.addImage(imgData, 'PNG', 20, y, imgWidth, imgHeight)
    pdf.save(`weekly-report-${report.value.start}-to-${report.value.end}.pdf`)
  } finally {
    downloading.value = false
  }
}
function goBack() {
  router.push({ name: 'reports' })
}

// If the id is invalid, redirect gracefully after mount
if (!report.value) {
  // Slight delay to allow store hydration if needed
  setTimeout(() => {
    if (!report.value) router.push({ name: 'reports' })
  }, 100)
}
</script>
<style scoped>
.report-detail {
  padding: 32px 80px 60px;
  background: #d9d9d9;
  font-family: Poppins, sans-serif;
}
.detail-container {
  background: #fff;
  max-width: 820px;
  margin: 0 auto;
  padding: 60px;
  box-shadow: 0 8px 28px -6px rgba(0, 0, 0, 0.08);
  border-radius: 4px;
  color: #000000;
}
.header-row {
  display: flex;
  justify-content: space-between;
  margin-bottom: 20px;
}
.back {
  background: #fff;
  border: 1px solid #cbd5e1;
  padding: 8px 16px;
  border-radius: 6px;
  cursor: pointer;
}
.back:hover {
  background: #f1f5f9;
}
.download {
  background: #063fd1;
  color: #fff;
  border: none;
  padding: 10px 22px;
  font-size: 14px;
  border-radius: 6px;
  cursor: pointer;
}
.download:disabled {
  opacity: 0.6;
  cursor: default;
}
.title {
  font-size: 22px;
  font-weight: 600;
  margin: 0 0 4px;
}
.subtitle {
  margin: 0 0 6px;
  font-size: 14px;
  line-height: 1.4;
}
.generated-by {
  font-size: 13px;
  margin: 0 0 18px;
}
hr {
  border: none;
  border-top: 1px solid #d4d4d4;
  margin: 26px 0;
}
.section-heading {
  font-size: 16px;
  font-weight: 600;
  margin: 0 0 14px;
}
.summary-list {
  list-style: none;
  padding: 0;
  margin: 0;
  font-size: 13px;
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.daily-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}
.daily-table th {
  text-align: left;
  background: #f8fafc;
  font-weight: 600;
  padding: 8px 10px;
  border-bottom: 1px solid #e2e8f0;
}
.daily-table td {
  padding: 8px 10px;
  border-bottom: 1px solid #eef2f6;
}
.rec-list {
  margin: 0;
  padding-left: 20px;
  font-size: 13px;
}
.not-found {
  text-align: center;
  padding: 40px;
  font-size: 14px;
}
</style>
